on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: build release
        run: cargo build --release
      - name: zip the release
        run: zip -j vsi.zip target/release/vsi.exe
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            vsi.zip
