on:
  push:
    tags:
      - "v*.*.*"

env:
  FS2020_SDK_LINK: https://storage.googleapis.com/msfs-sdk/MSFS_SDK_Core_Installer_0.16.0.0.msi
  FS2020_SDK_SAMPLE_LINK: https://storage.googleapis.com/msfs-sdk/MSFS_SDK_Samples_Installer_0.16.0.0.msi

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: install msfs sdk
        uses: ./msfs-sdk-action
        with:
          sdk_url: ${{ env.FS2020_SDK_LINK }}
          sample_sdk_url: ${{ env.FS2020_SDK_SAMPLE_LINK }}
      - name: build release
        run: cargo build --release
      - name: zip the release
        run: zip -j vsi.zip target/release/vsi.exe
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            vsi.zip
